"""add_content_moderation_and_updated_at

Revision ID: 73f45297ba0c
Revises: 95c4e562421a
Create Date: 2026-06-02 19:50:47.904684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f45297ba0c'
down_revision: Union[str, Sequence[str], None] = '95c4e562421a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_moderation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_version', sa.String(length=64), nullable=False),
    sa.Column('trigger_action', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moderation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.trace_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'target_version', name='uq_cm_record_version'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_cm_records_status', 'content_moderation_records', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_cm_records_target', 'content_moderation_records', ['target_type', 'target_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_cm_records_task', 'content_moderation_records', ['task_id'], unique=True)
    op.create_index('idx_cm_records_trace', 'content_moderation_records', ['trace_id'], unique=False)
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('forum_replies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('forum_zones', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('forum_zones', 'updated_at')
    op.drop_column('forum_replies', 'updated_at')
    op.drop_column('comments', 'updated_at')
    op.drop_index('idx_cm_records_trace', table_name='content_moderation_records')
    op.drop_index('idx_cm_records_task', table_name='content_moderation_records')
    op.drop_index('idx_cm_records_target', table_name='content_moderation_records')
    op.drop_index('idx_cm_records_status', table_name='content_moderation_records')
    op.drop_table('content_moderation_records')
    # ### end Alembic commands ###
